<a href="https://colab.research.google.com/github/zzhu104/MAT494_HW/blob/main/HW1.2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

HW1.2

In [1]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
a = np.zeros(10)
b = np.ones(10)
c = np.zeros(10) + 5
print(a)
print(b)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [3]:
# use random numbers to populate an array
a = np.random.rand(10)
print(a)

[0.67426143 0.01935157 0.45569443 0.49954931 0.75727566 0.91363395
 0.42511745 0.53034519 0.4622107  0.54907455]


In [4]:
# index
a = np.arange(10)
print(a)
print(a[-1])
print(a[1:3])
print(a[1:5:2])

[0 1 2 3 4 5 6 7 8 9]
9
[1 2]
[1 3]


In [5]:
a = np.zeros((3, 5))
# note the extra bracket you need for calling np.zeros
print(a, '\n')

# shape of the array
print('len =',len(a))
print('shape =',a.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

len = 3
shape = (3, 5)


In [6]:
# pick two output valuables from a method
a = np.zeros((3,5))
nx,ny = a.shape
print('nx =', nx)
print('ny =', ny)

nx = 3
ny = 5


In [7]:
# ways to generate a constant array

a = np.zeros((3,5)) + 7
print(a, '\n')

b = np.ones((3,5)) * 7
print(b, '\n')

c = np.full((3,5), 7)
print(c)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]] 

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [8]:
# identity matrix function eye()
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
# index
a = np.array(([1,2], [3,4], [5,6]))
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
# slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[:2, 1:3]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [11]:
# mix integer and slice index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
b = a[1, :]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]


In [12]:
# use two list as index
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a, '\n')
print(a[[0,1,2],[2,1,2]])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[ 3  6 11]


In [13]:
# update values
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[1,:] += 10
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[ 0.  1.  2.]
 [10. 11. 12.]
 [ 0.  1.  2.]]


In [14]:

a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print('before\n',a)

a[:,2] = 5.
print('after\n',a)

before
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
after
 [[0. 1. 5.]
 [0. 1. 5.]
 [0. 1. 5.]]


In [15]:

# type of data in the array
a=np.array(([1,1],[1,1]))
print(a)
print(a.dtype)

[[1 1]
 [1 1]]
int64


In [16]:
a=np.array(([1.,1],[1,1]))
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64


In [17]:

a=np.array(([1.,1],[1,1]))>2
print(a)
print(a.dtype)

[[False False]
 [False False]]
bool


In [18]:
a=np.array((['1','1'],['1','1']))
print(a)
print(a.dtype)

[['1' '1']
 ['1' '1']]
<U1


In [19]:
a=np.array((['1','1'],['1','1']),dtype=float)
print(a)
print(a.dtype)

[[1. 1.]
 [1. 1.]]
float64


Elementwise calculation using array

One array

In [20]:
# most numpy functions can be applied directly to an array
a = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
print(a)
print(a >= 1)
print(np.sqrt(a))

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
[[False  True  True]
 [False  True  True]
 [False  True  True]]
[[0.         1.         1.41421356]
 [0.         1.         1.41421356]
 [0.         1.         1.41421356]]


Inversion

In [21]:
# inversion
A = np.matrix([[1,0,0],
               [0,1,0],
               [0,0,1]])

B = np.matrix([[3,1],
               [1,3]])

print(A, '\n')
print(np.trace(A), '\n')
print(np.invert(A), '\n')

print(B, '\n')
print(np.trace(B), '\n')
print(np.invert(B))

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

3 

[[-2 -1 -1]
 [-1 -2 -1]
 [-1 -1 -2]] 

[[3 1]
 [1 3]] 

6 

[[-4 -2]
 [-2 -4]]


Eigenvalues and eigenvectors of the square matrix

In [22]:
# numpy.linalg.eig(a)     Calculate the eigenvalues and eigenvectors of the square matrix.
# numpy.linalg.eigvals(a) Calculate the eigenvalues of the square matrix.

x = np.diag([1,2,3])
print(np.linalg.eigvals(x))

a, b = np.linalg.eig(x)
print('eigenvalue：', a, '\n')
print('eigenvector：\n', b, '\n')


# verify that the eigenvalues and eigenvectors are correct
for i in range(3):       
    if np.allclose(a[i] * b[:, i], np.dot(x, b[:, i])):
        print('Correct')
    else:
        print('Wrong')

[1. 2. 3.]
eigenvalue： [1. 2. 3.] 

eigenvector：
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Correct
Correct
Correct


Two arrays

In [23]:
# two arrays
a = np.zeros((3,3))
b = np.zeros((3,3))
for i in range(3):
    a[:,i] = i
    b[i,:] = i
print('a=\n', a)
print('b=\n', b)

print('a+b=\n', a + b)
print('a*b=\n', a * b)
print('a/b=\n', a / b) # notice the first row of the result

a=
 [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
b=
 [[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]
a+b=
 [[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]]
a*b=
 [[0. 0. 0.]
 [0. 1. 2.]
 [0. 2. 4.]]
a/b=
 [[nan inf inf]
 [0.  1.  2. ]
 [0.  0.5 1. ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: divide by zero encountered in true_divide
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == '':


In [24]:
# broadcasting
# add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([2, 0, 1])
y = x + v
z = x * v
print(y, '\n')
print(z)

[[ 3  2  4]
 [ 6  5  7]
 [ 9  8 10]
 [12 11 13]] 

[[ 2  0  3]
 [ 8  0  6]
 [14  0  9]
 [20  0 12]]


In [25]:
# dot product
x = np.array([1,2,3,4,5])
y = np.array([2,3,4,5,6])
z = np.dot(x,y)  #  The dot product of two vectors
print(z)

x = np.array([[1,2,3],[3,4,5],[6,7,8]])
y = np.array([[5,4,2],[1,7,9],[0,4,5]])
z= np.dot(x,y)   #  matrix multiplication
print(z)

70
[[  7  30  35]
 [ 19  60  67]
 [ 37 105 115]]


In [26]:
a = np.array([1,2])
b = np.array([3,4]) 
c = np.array([[3],[4]])

print(b*a) 
print(a*c)  #  A matrix multiplies its elements, so it satisfies the commutative law
print(c*a)

print(np.dot(a,b))    #  matrix multiplication
print(np.dot(a,c))
#print(np.dot(c,a)) There will be an error

[3 8]
[[3 6]
 [4 8]]
[[3 6]
 [4 8]]
11
[11]


In [27]:
# cross product
a = [1,2,3]
b = [2,3,4]

c = np.cross(a,b)
print(c)

[-1  2 -1]


In [28]:
# matrix multiplication
a = np.array([[1,2], [3,4]])
b = np.array([[2,3], [4,5]])

c = np.matmul(a,b)
print(c)

[[10 13]
 [22 29]]


Reshape array

In [29]:
# transpose
a = np.array(([1,2], [3,4],[ 5,6]))
print('a=\n',a)
print('a.T=\n',a.T)
print('a.transpose()=\n',a.transpose())

a=
 [[1 2]
 [3 4]
 [5 6]]
a.T=
 [[1 3 5]
 [2 4 6]]
a.transpose()=
 [[1 3 5]
 [2 4 6]]


In [30]:
# reshape
a = np.array(([1,2], [3,4], [5,6]))
print('a\n', a)

b = a.reshape((2,3))
print('b\n', b)

c = a.flatten()
print('c\n', c)

# C order, row order
d = a.flatten(order = 'C')
print('d\n', d)

# Fortran order, column order
e = a.flatten(order = 'F')
print('e\n', e)

a
 [[1 2]
 [3 4]
 [5 6]]
b
 [[1 2 3]
 [4 5 6]]
c
 [1 2 3 4 5 6]
d
 [1 2 3 4 5 6]
e
 [1 3 5 2 4 6]


In [31]:
# stacking
a=np.full((3,2),1.)
b=np.full((3,2),2.)
c=np.full((3,2),3.)

print('a=',a)
print('b=',b)
print('c=',c)

print('hstack=',np.hstack((a,b,c)))
print('vstack=',np.vstack((a,b,c)))

a= [[1. 1.]
 [1. 1.]
 [1. 1.]]
b= [[2. 2.]
 [2. 2.]
 [2. 2.]]
c= [[3. 3.]
 [3. 3.]
 [3. 3.]]
hstack= [[1. 1. 2. 2. 3. 3.]
 [1. 1. 2. 2. 3. 3.]
 [1. 1. 2. 2. 3. 3.]]
vstack= [[1. 1.]
 [1. 1.]
 [1. 1.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


Large array

In [32]:
# difference of python sum and numpy.sum

data = np.arange(1000)

%timeit sum(data)
%timeit np.sum(data)

10000 loops, best of 5: 174 µs per loop
The slowest run took 15.11 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 5.17 µs per loop


In [33]:
data = []
for i in range(1000):
    data.append(i)

%timeit sum(data)
%timeit np.sum(data)

100000 loops, best of 5: 6.58 µs per loop
10000 loops, best of 5: 101 µs per loop


Solving problems

Polynomial

In [34]:
a = np.array([[8, -6, 2], [-4, 11, -7], [4, -7, 6]])
b = np.array([[28], [-40], [33]])
x = np.linalg.solve(a, b)
print(a)
print(x)

[[ 8 -6  2]
 [-4 11 -7]
 [ 4 -7  6]]
[[ 2.]
 [-1.]
 [ 3.]]


In [35]:
m = np.array([[1, -2, 1],[0, 2, -8],[-4, 5, 9]])
v = np.array([0, 8, -9])
r = np.linalg.solve(m, v)
print('result：')
name = ['X1', 'X2', 'X3']
for i in range(len(name)):
    print(name[i] + '=' + str(r[i]))

result：
X1=29.0
X2=16.0
X3=3.0


In [36]:
mat = np.vstack([[1,1,1],[1,-1,2],[2,0,3]])
sol = np.vstack([3,2,1])
try:
    npl.solve(mat,sol)
except:
    print(np.hstack([mat,sol]))
    print('Not solveable. Adding rows 1 and 2 contradicts row 3.')

[[ 1  1  1  3]
 [ 1 -1  2  2]
 [ 2  0  3  1]]
Not solveable. Adding rows 1 and 2 contradicts row 3.


Determine whether the matrix is positive and definite

In [37]:
# (whether all eigenvalues are positive)
A = np.arange(16).reshape(4,4)
print(A)

A = A + A.T  # Convert square matrices to symmetric matrices
print(A)

B = np.linalg.eigvals(A)
print(B)

if np.all(B>0):
    print('Yes')
else:
    print('No')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]
[ 6.74165739e+01+0.00000000e+00j -7.41657387e+00+0.00000000e+00j
  1.32429523e-15+2.79902006e-15j  1.32429523e-15-2.79902006e-15j]
No


QR decomposition

In [38]:
#coding:utf8

def gram_schmidt(A):
    """Gram-schmidt Orthogonalization"""
    Q=np.zeros_like(A)
    cnt = 0
    for a in A.T:
        u = np.copy(a)
        for i in range(0, cnt):
            u -= np.dot(np.dot(Q[:, i].T, a), Q[:, i]) 
        e = u / np.linalg.norm(u)  # normalization 
        Q[:, cnt] = e
        cnt += 1
    R = np.dot(Q.T, A)
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]], dtype = float)

(Q, R) = gram_schmidt(A)
print(Q)
print(R)
print(np.dot(Q, R))

[[ 0.647   0.5096  0.1799]
 [ 0.5392 -0.4811  0.5743]
 [ 0.5392 -0.1305 -0.7902]
 [ 0.      0.7013  0.1162]]
[[ 9.2736  3.235  -5.3916]
 [ 0.      5.7039  2.006 ]
 [-0.      0.     13.7079]]
[[  6.   5.   0.]
 [  5.  -1.   4.]
 [  5.   1. -14.]
 [  0.   4.   3.]]


In [39]:
def givens_rotation(A):
    """"Givens Rotations"""
    (r, c) = np.shape(A)
    Q = np.identity(r)
    R = np.copy(A)
    (rows, cols) = np.tril_indices(r, -1, c)
    for (row, col) in zip(rows, cols):
        if R[row, col] != 0:  
            r_ = np.hypot(R[col, col], R[row, col])  # d
            c = R[col, col]/r_
            s = -R[row, col]/r_
            G = np.identity(r)
            G[[col, row], [col, row]] = c
            G[row, col] = s
            G[col, row] = -s
            R = np.dot(G, R)   # R=G(n-1,n)*...*G(2n)*...*G(23,1n)*...*G(12)*A
            Q = np.dot(Q, G.T)  # Q=G(n-1,n).T*...*G(2n).T*...*G(23,1n).T*...*G(12).T
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]], dtype = float)

(Q, R) = givens_rotation(A)
print(Q)
print(R)
print (np.dot(Q, R))

[[ 0.647   0.5096  0.1799 -0.5379]
 [ 0.5392 -0.4811  0.5743  0.3848]
 [ 0.5392 -0.1305 -0.7902  0.2607]
 [ 0.      0.7013  0.1162  0.7034]]
[[ 9.2736  3.235  -5.3916]
 [ 0.      5.7039  2.006 ]
 [-0.      0.     13.7079]
 [-0.     -0.      0.    ]]
[[  6.   5.   0.]
 [  5.  -1.   4.]
 [  5.   1. -14.]
 [  0.   4.   3.]]


In [40]:
def householder_reflection(A):
    """Householder Triangularization"""
    (r, c) = np.shape(A)
    Q = np.identity(r)
    R = np.copy(A)
    for cnt in range(r - 1):
        x = R[cnt:, cnt]
        e = np.zeros_like(x)
        e[0] = np.linalg.norm(x)
        u = x - e
        v = u / np.linalg.norm(u)
        Q_cnt = np.identity(r)
        Q_cnt[cnt:, cnt:] -= 2.0 * np.outer(v, v)
        R = np.dot(Q_cnt, R)  # R=H(n-1)*...*H(2)*H(1)*A
        Q = np.dot(Q, Q_cnt)  # Q=H(n-1)*...*H(2)*H(1)  H is the self inverse matrix
    return (Q, R)

np.set_printoptions(precision=4, suppress=True)
A = np.array([[6, 5, 0],[5, -1, 4],[5, 1, -14],[0, 4, 3]], dtype = float)

(Q, R) = householder_reflection(A)
print(Q)
print(R)
print(np.dot(Q, R))

[[ 0.647   0.5096  0.1799  0.5379]
 [ 0.5392 -0.4811  0.5743 -0.3848]
 [ 0.5392 -0.1305 -0.7902 -0.2607]
 [ 0.      0.7013  0.1162 -0.7034]]
[[ 9.2736  3.235  -5.3916]
 [ 0.      5.7039  2.006 ]
 [-0.      0.     13.7079]
 [ 0.      0.      0.    ]]
[[  6.   5.   0.]
 [  5.  -1.   4.]
 [  5.   1. -14.]
 [ -0.   4.   3.]]
